name: Release

on:
  push:
    branches:
      - ci/*
    tags:
      - '*'

jobs:
  linux-cli-binary:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20.5'
    - run: |
        sudo apt-get install -y sqlite3
        npm install
        npm run build
        nix-build ledger.nix
        cp ./result/bin/ledger internal/binary/ledger
        go build
        cp paisa paisa-cli-linux-amd64
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          paisa-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  linux-app-binary:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20.5'
    - run: |
        sudo apt-get install -y sqlite3 libgtk-3-dev libwebkit2gtk-4.0-dev build-essential pkg-config
        npm install
        npm run build
        nix-build ledger.nix
        cp ./result/bin/ledger internal/binary/ledger
        go build
        cp paisa paisa-cli-linux-amd64
        cd desktop
        go install github.com/wailsapp/wails/v2/cmd/wails@latest
        wails doctor
        wails build -tags webkit2_40
        cp build/bin/Paisa build/linux/usr/local/bin
        cp -r build/linux paisa_0.5.2_amd64
        dpkg --build paisa_0.5.2_amd64
        cd ..
        mv desktop/paisa_0.5.2_amd64.deb paisa-app-linux-amd64.deb
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          paisa-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  mac-binary:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20.5'
    - run: |
        brew install --force --overwrite sqlite3 create-dmg
        brew install --build-from-source --verbose ./ledger.rb
        cp "$(brew --prefix ledger)/bin/ledger" internal/binary/ledger
        npm install
        npm run build
        go build
        cp paisa paisa-cli-macos-amd64
        cd desktop
        go install github.com/wailsapp/wails/v2/cmd/wails@latest
        wails build
        create-dmg --volname "Paisa" --window-pos 200 120 --window-size 800 400 --icon-size 100  --icon "Paisa.app" 200 190 --app-drop-link 600 185 --hide-extension "Paisa.app" --volicon build/bin/Paisa.app/Contents/Resources/iconfile.icns  "Paisa.dmg" build/bin/Paisa.app
        cd ..
        cp desktop/Paisa.dmg paisa-app-macos-amd64.dmg
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          paisa-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  windows-binary:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20.5'
    - run: |
        choco install sqlite
        choco install wget
        choco install nsis
        npm install
        npm run build
        wget https://github.com/FullofQuarks/Windows-Ledger-Binaries/releases/download/v3.3.2/ledger.exe
        cp ledger.exe internal/binary/ledger
        go build
        cp paisa.exe paisa-cli-windows-amd64.exe
        $env:PATH += ";C:\Program Files (x86)\NSIS\Bin"
        cd desktop
        go install github.com/wailsapp/wails/v2/cmd/wails@latest
        wails build -tags webkit2_40 -nsis -webview2 embed
        cd ..
        cp .\desktop\build\bin\paisa-amd64-installer.exe paisa-app-windows-amd64.exe
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          paisa-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
